# Generated by Django 4.1.7 on 2023-04-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_ca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('rut', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.categoria')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.venta')),
                ('rut_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.cliente')),
            ],
        ),
    ]
