# Generated by Django 4.1.7 on 2023-04-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='sku_producto',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
