# Generated by Django 4.1.7 on 2023-04-02 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0002_remove_producto_venta_remove_venta_id_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='sku_producto',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ListaDeseo',
            fields=[
                ('id_deseo', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.producto')),
            ],
        ),
    ]
