# Generated by Django 4.1.7 on 2023-04-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0003_remove_producto_sku_producto_sku_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='email',
        ),
    ]
