# Generated by Django 4.1.7 on 2023-04-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ruta_img',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
