# Generated by Django 4.1.7 on 2023-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0007_producto_ruta_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ruta_img',
            field=models.CharField(max_length=200),
        ),
    ]
