# Generated by Django 4.1.7 on 2023-04-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0009_alter_producto_ruta_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='ruta_img',
            new_name='img',
        ),
    ]
