# Generated by Django 4.1.7 on 2023-04-22 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0010_rename_ruta_img_producto_img'),
    ]

    operations = [
    ]
