# Generated by Django 4.1.7 on 2023-04-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0011_auto_20230422_1746'),
    ]

    operations = [
    ]
