# Generated by Django 4.1.7 on 2023-04-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0012_auto_20230422_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img',
        ),
    ]
