# Generated by Django 4.1.7 on 2023-04-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0013_remove_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
