# Generated by Django 4.1.7 on 2023-05-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0014_producto_link_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MYWEB1.venta')),
            ],
        ),
    ]
