# Generated by Django 4.1.7 on 2023-06-29 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0016_region_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadeseo',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
