# Generated by Django 4.1.7 on 2023-06-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0017_alter_listadeseo_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadeseo',
            name='id_cliente',
            field=models.IntegerField(),
        ),
    ]
