# Generated by Django 4.1.7 on 2023-07-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYWEB1', '0018_alter_listadeseo_id_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
